# Generated by Django 5.2.7 on 2026-05-27 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_initial'),
        ('students', '0001_initial'),
        ('timetable', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='units.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'unit', 'term')},
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='curriculum_unit',
        ),
    ]
