# Generated by Django 5.2.7 on 2026-05-22 13:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('departments', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(db_index=True, help_text='Unique student registration number (e.g., STU2024001)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_registration_number', message='Registration number must contain only uppercase letters, numbers, and hyphens', regex='^[A-Z0-9\\-]+$')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be valid international format', regex='^\\+?1?\\d{9,15}$')])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('current_study_year', models.PositiveSmallIntegerField(default=1, help_text='Current year of study (1-based)')),
                ('current_semester', models.PositiveSmallIntegerField(default=1, help_text='Current semester (1-based)')),
                ('admission_year', models.PositiveIntegerField(help_text='Year of admission (e.g., 2024)')),
                ('academic_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('on_leave', 'On Leave')], db_index=True, default='active', help_text='Current academic status', max_length=20)),
                ('enrollment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('distance_learning', 'Distance Learning'), ('sandwich', 'Sandwich'), ('block_release', 'Block Release')], default='full_time', help_text='Type of enrollment', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the student is currently active')),
                ('profile_photo', models.ImageField(blank=True, help_text='Student profile photograph', null=True, upload_to='students/photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text="Department offering the student's program", on_delete=django.db.models.deletion.PROTECT, related_name='students', to='departments.department')),
                ('faculty', models.ForeignKey(blank=True, help_text='Faculty/College the student belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty_students', to='departments.department')),
                ('program', models.ForeignKey(help_text='Academic program the student is enrolled in', on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_students', to='programs.program')),
                ('user', models.OneToOneField(help_text='Link to user account for authentication', on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='AcademicProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(db_index=True, help_text="Academic year (e.g., '2024/2025')", max_length=20)),
                ('study_year', models.PositiveSmallIntegerField(help_text='Year of study during this period')),
                ('semester', models.PositiveSmallIntegerField(help_text='Semester during this period (1 or 2)')),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, help_text='Semester GPA (0.00-4.00)', max_digits=4)),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, help_text='Cumulative GPA (0.00-4.00)', max_digits=4)),
                ('total_credits', models.PositiveIntegerField(default=0, help_text='Total credit hours completed')),
                ('credits_this_semester', models.PositiveIntegerField(default=0, help_text='Credit hours completed this semester')),
                ('academic_status', models.CharField(choices=[('good_standing', 'Good Standing'), ('warning', 'Academic Warning'), ('probation', 'Academic Probation'), ('suspension', 'Suspension'), ('dismissed', 'Dismissed')], default='good_standing', help_text='Academic standing for this period', max_length=20)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded this progress', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_academic_progress', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student whose progress this record tracks', on_delete=django.db.models.deletion.CASCADE, related_name='academic_progress', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year', '-study_year', '-semester'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(db_index=True, help_text='Academic year of enrollment', max_length=20)),
                ('study_year', models.PositiveSmallIntegerField(help_text='Year of study')),
                ('semester', models.PositiveSmallIntegerField(help_text='Semester (1 or 2)')),
                ('enrollment_status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('failed', 'Failed'), ('suspended', 'Suspended'), ('deferred', 'Deferred to Next Semester')], db_index=True, default='enrolled', help_text='Current enrollment status', max_length=20)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, help_text='Date of enrollment')),
                ('notes', models.TextField(blank=True, help_text='Additional notes (e.g., reason for withdrawal)')),
                ('curriculum', models.ForeignKey(help_text='Curriculum being enrolled in', on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='curriculum.curriculum')),
                ('student', models.ForeignKey(help_text='Student enrolling in curriculum', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year', '-study_year', '-semester'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['registration_number'], name='students_st_registr_23d894_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='students_st_email_e271bc_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department', 'program'], name='students_st_departm_1820e5_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['academic_status', 'is_active'], name='students_st_academi_c3d977_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_year'], name='students_st_admissi_307101_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_study_year', 'current_semester'], name='students_st_current_02baa7_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('registration_number',), name='uq_student_registration_number'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('email',), name='uq_student_email'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('current_study_year__gte', 1)), name='ck_student_current_study_year_positive'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('current_semester__gte', 1)), name='ck_student_current_semester_positive'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('admission_year__gte', 1900)), name='ck_student_admission_year_valid'),
        ),
        migrations.AddIndex(
            model_name='academicprogress',
            index=models.Index(fields=['student', 'academic_year'], name='students_ac_student_bc03fc_idx'),
        ),
        migrations.AddIndex(
            model_name='academicprogress',
            index=models.Index(fields=['student', '-semester'], name='students_ac_student_263b46_idx'),
        ),
        migrations.AddIndex(
            model_name='academicprogress',
            index=models.Index(fields=['academic_status'], name='students_ac_academi_9dec4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicprogress',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'study_year', 'semester'), name='uq_academic_progress_student_period'),
        ),
        migrations.AddConstraint(
            model_name='academicprogress',
            constraint=models.CheckConstraint(condition=models.Q(('gpa__gte', 0), ('gpa__lte', 4)), name='ck_academic_progress_gpa_range'),
        ),
        migrations.AddConstraint(
            model_name='academicprogress',
            constraint=models.CheckConstraint(condition=models.Q(('cgpa__gte', 0), ('cgpa__lte', 4)), name='ck_academic_progress_cgpa_range'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['student', 'academic_year'], name='students_st_student_653460_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['curriculum', 'academic_year'], name='students_st_curricu_a6b23f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['enrollment_status'], name='students_st_enrollm_b5fa1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'curriculum', 'academic_year', 'study_year', 'semester'), name='uq_student_enrollment_period'),
        ),
    ]
