# Generated by Django 5.1 on 2026-09-14 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('programs', '0001_initial'),
        ('students', '0001_initial'),
        ('timetable', '0003_timetableslot_lecturer_name_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicprogress',
            options={'verbose_name': 'Academic Progress', 'verbose_name_plural': 'Academic Progress Reports'},
        ),
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ['-academic_year', '-semester'], 'verbose_name': 'Student Enrollment', 'verbose_name_plural': 'Student Enrollments'},
        ),
        migrations.RemoveConstraint(
            model_name='academicprogress',
            name='uq_academic_progress_student_period',
        ),
        migrations.RemoveConstraint(
            model_name='academicprogress',
            name='ck_academic_progress_gpa_range',
        ),
        migrations.RemoveConstraint(
            model_name='academicprogress',
            name='ck_academic_progress_cgpa_range',
        ),
        migrations.RemoveConstraint(
            model_name='studentenrollment',
            name='uq_student_enrollment_period',
        ),
        migrations.RemoveIndex(
            model_name='academicprogress',
            name='students_ac_student_bc03fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='academicprogress',
            name='students_ac_student_263b46_idx',
        ),
        migrations.RemoveIndex(
            model_name='academicprogress',
            name='students_ac_academi_9dec4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentenrollment',
            name='students_st_student_653460_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentenrollment',
            name='students_st_curricu_a6b23f_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentenrollment',
            name='students_st_enrollm_b5fa1c_idx',
        ),
        migrations.RemoveField(
            model_name='academicprogress',
            name='credits_this_semester',
        ),
        migrations.RemoveField(
            model_name='academicprogress',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='notes',
        ),
        migrations.AddField(
            model_name='academicprogress',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='combination',
            field=models.CharField(blank=True, help_text='Subject combination or major/minor option (e.g., Mathematics/Chemistry)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='timetable_group',
            field=models.CharField(blank=True, help_text='Timetable group or stream tag (e.g., GR K, Group 3, GR F)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='academic_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='timetable.academicterm'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='academicprogress',
            name='academic_status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='academicprogress',
            name='academic_year',
            field=models.CharField(default='2024/2025', max_length=10),
        ),
        migrations.AlterField(
            model_name='academicprogress',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='academicprogress',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='academicprogress',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='academicprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_progress', to='students.student'),
        ),
        migrations.AlterField(
            model_name='academicprogress',
            name='study_year',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='academicprogress',
            name='total_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='academic_year',
            field=models.CharField(default='2024/2025', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_status',
            field=models.CharField(default='enrolled', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='study_year',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['timetable_group'], name='students_st_timetab_225351_idx'),
        ),
        migrations.AlterModelTable(
            name='academicprogress',
            table='student_academic_progress',
        ),
        migrations.AlterModelTable(
            name='studentenrollment',
            table='student_enrollment',
        ),
    ]
