# Generated by Django 5.1 on 2026-09-16 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_academicprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(db_index=True, help_text='Unique student registration number (e.g., STU2024001 or ABT5/10954/24)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_registration_number', message='Registration number must contain only uppercase letters, numbers, hyphens, and slashes', regex='^[A-Z0-9\\-/]+$')]),
        ),
    ]
