# Generated by Django 5.2.7 on 2026-05-22 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('departments', '0001_initial'),
        ('lecturers', '0001_initial'),
        ('programs', '0001_initial'),
        ('rooms', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField(help_text='Session start time (e.g., 08:00)')),
                ('end_time', models.TimeField(help_text='Session end time (e.g., 10:00)')),
                ('slot_name', models.CharField(help_text='Descriptive name (e.g., Morning Slot 1, Afternoon Session)', max_length=255)),
                ('duration_minutes', models.PositiveSmallIntegerField(help_text='Duration of slot in minutes')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', help_text='Current operational status', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about this time slot')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'db_table': 'timetable_timeslot',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['start_time'], name='timetable_t_start_t_718626_idx'), models.Index(fields=['status'], name='timetable_t_status_4d003d_idx')],
                'unique_together': {('start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_group', models.CharField(default='MAIN', max_length=50)),
                ('curriculum_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='curriculum.curriculumunit')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_slots', to='lecturers.lecturer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_slots', to='rooms.room')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='timetable.academicterm')),
            ],
            options={
                'ordering': ['term', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimetableConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conflict_type', models.CharField(choices=[('room', 'Room Conflict'), ('lecturer', 'Lecturer Conflict'), ('program', 'Program Conflict')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.academicterm')),
                ('slot_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_primary', to='timetable.timetableslot')),
                ('slot_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_secondary', to='timetable.timetableslot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimetableUploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(upload_to='timetable_uploads/%Y/%m/%d')),
                ('status', models.CharField(choices=[('received', 'Received'), ('validated', 'Validated'), ('failed', 'Failed'), ('processed', 'Processed')], default='received', max_length=20)),
                ('rows_received', models.PositiveIntegerField(default=0)),
                ('rows_saved', models.PositiveIntegerField(default=0)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='upload_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='timetable.timetableuploadbatch'),
        ),
        migrations.CreateModel(
            name='TimetableSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024/2025)', max_length=10)),
                ('study_year', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Year of study (1-5)')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], help_text='Semester (1 or 2)')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], help_text='Day when class occurs', max_length=3)),
                ('session_type', models.CharField(choices=[('lecture', 'Lecture'), ('practical', 'Practical/Lab'), ('tutorial', 'Tutorial'), ('seminar', 'Seminar'), ('workshop', 'Workshop'), ('project', 'Project'), ('field_work', 'Field Work')], default='lecture', help_text='Type of teaching session', max_length=20)),
                ('delivery_mode', models.CharField(choices=[('face_to_face', 'Face-to-Face'), ('online', 'Online'), ('hybrid', 'Hybrid'), ('blended', 'Blended')], default='face_to_face', help_text='How session is delivered', max_length=20)),
                ('student_group', models.CharField(blank=True, help_text='Student group/cohort identifier (e.g., Group A, Set 1)', max_length=100)),
                ('max_students', models.PositiveSmallIntegerField(help_text='Maximum number of students for this session')),
                ('current_enrollment', models.PositiveSmallIntegerField(default=0, help_text='Current enrolled students')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='scheduled', help_text='Current session status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions for the session')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetable_sessions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department offering this session', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_sessions', to='departments.department')),
                ('lecturer', models.ForeignKey(blank=True, help_text='Lecturer assigned to teach this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_sessions', to='lecturers.lecturer')),
                ('program', models.ForeignKey(help_text='Program this session is offered under (enables filtering)', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_sessions', to='programs.program')),
                ('room', models.ForeignKey(blank=True, help_text='Room/venue where session occurs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_sessions', to='rooms.room')),
                ('time_slot', models.ForeignKey(help_text='Time slot for this session', on_delete=django.db.models.deletion.PROTECT, related_name='timetable_sessions', to='timetable.timeslot')),
                ('unit', models.ForeignKey(help_text='Unit/course being taught in this session', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_sessions', to='units.unit')),
            ],
            options={
                'verbose_name': 'Timetable Session',
                'verbose_name_plural': 'Timetable Sessions',
                'db_table': 'timetable_session',
                'ordering': ['day_of_week', 'time_slot__start_time'],
                'indexes': [models.Index(fields=['academic_year', 'semester'], name='timetable_s_academi_71f0ff_idx'), models.Index(fields=['program', 'study_year', 'semester'], name='timetable_s_program_3951c7_idx'), models.Index(fields=['department', 'day_of_week'], name='timetable_s_departm_bd74eb_idx'), models.Index(fields=['lecturer', 'day_of_week'], name='timetable_s_lecture_d1b0b7_idx'), models.Index(fields=['room', 'day_of_week'], name='timetable_s_room_id_7795dd_idx'), models.Index(fields=['day_of_week', 'time_slot'], name='timetable_s_day_of__58838d_idx'), models.Index(fields=['status'], name='timetable_s_status_0af423_idx'), models.Index(fields=['unit'], name='timetable_s_unit_id_a741b5_idx')],
                'unique_together': {('unit', 'program', 'study_year', 'semester', 'day_of_week', 'time_slot', 'student_group', 'academic_year')},
            },
        ),
    ]
