# Generated by Django 5.1 on 2026-06-30 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='TimetableUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(upload_to='timetable_uploads/%Y/%m/')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('done', 'Done'), ('partial', 'Partial — some rows failed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('rows_received', models.PositiveIntegerField(default=0)),
                ('rows_saved', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='timetable.academicterm')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('credit_hours', models.PositiveSmallIntegerField(default=3)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='core.department')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_of_study', models.PositiveSmallIntegerField(default=1)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_slots', to='core.lecturer')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='core.program')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_slots', to='core.room')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='timetable.academicterm')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='timetable.unit')),
            ],
            options={
                'ordering': ['term', 'day', 'start_time'],
                'indexes': [models.Index(fields=['term', 'unit'], name='timetable_t_term_id_a5e6a0_idx'), models.Index(fields=['term', 'program', 'year_of_study'], name='timetable_t_term_id_45e4d1_idx'), models.Index(fields=['day', 'start_time'], name='timetable_t_day_8f8ffb_idx')],
            },
        ),
    ]
