# Generated by Django 5.2.14 on 2026-05-09 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('lecturers', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_group', models.CharField(default='MAIN', max_length=50)),
                ('curriculum_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='curriculum.curriculumunit')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_slots', to='lecturers.lecturer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_slots', to='rooms.room')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='timetable.academicterm')),
            ],
            options={
                'ordering': ['term', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimetableConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conflict_type', models.CharField(choices=[('room', 'Room Conflict'), ('lecturer', 'Lecturer Conflict'), ('program', 'Program Conflict')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.academicterm')),
                ('slot_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_primary', to='timetable.timetableslot')),
                ('slot_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_secondary', to='timetable.timetableslot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimetableUploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(upload_to='timetable_uploads/%Y/%m/%d')),
                ('status', models.CharField(choices=[('received', 'Received'), ('validated', 'Validated'), ('failed', 'Failed'), ('processed', 'Processed')], default='received', max_length=20)),
                ('rows_received', models.PositiveIntegerField(default=0)),
                ('rows_saved', models.PositiveIntegerField(default=0)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='upload_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='timetable.timetableuploadbatch'),
        ),
    ]
