# Generated by Django 5.2.7 on 2026-05-27 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('timetable', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableslot',
            name='curriculum_unit',
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='programs.program'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='units.unit'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
