# Generated by Django 5.1 on 2026-08-23 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_slots', to='lecturers.lecturer'),
        ),
    ]
