# Generated by Django 5.1 on 2026-08-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_timetableslot_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='lecturer_name_text',
            field=models.CharField(blank=True, default='', help_text='Fallback display name for the lecturer when no linked Lecturer account exists yet (e.g. parsed from a document but not yet matched to a registered account).', max_length=255),
        ),
    ]
