# Generated by Django 5.1 on 2026-09-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_timetableslot_lecturer_name_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableuploadbatch',
            name='rows_failed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]