# Generated by Django 5.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_timetableuploadbatch_rows_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='stream',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
