# Generated by Django 5.1 on 2026-09-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_timetableslot_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='stream',
            field=models.CharField(blank=True, default='', help_text="Numbered sub-stream of this program+year+semester cohort as printed on the master timetable, e.g. the '1' in 'BED.MATH/CHEM Y3S1(1)'. Blank when the cohort has only one stream. Unlike class_group (which varies per shared unit pool - e.g. GR_J for one pool, GR_C for another, within the same stream), this identifies the single physical row/class the slot was printed under, so a student's whole stream can be selected as one consistent set regardless of how many different class_group letters its units individually use.", max_length=10),
        ),
    ]
