# Generated by Django 5.1 on 2026-06-30 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_units', to='timetable.academicterm')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='timetable.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['unit__code'],
                'unique_together': {('user', 'unit', 'term')},
            },
        ),
    ]
