# Generated by Django 5.1 on 2026-09-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentunit',
            name='class_group',
            field=models.CharField(blank=True, default='', help_text="The student's own elective/practical group for this unit (e.g. 'GR B'), when the unit is split into more than one such group. Different unit pools within the same stream can use unrelated group letters at once (see TimetableSlot.stream docstring), so this is set per-unit rather than once for the whole stream. Blank means either the unit isn't split, or the student hasn't picked yet - see apps.schedule.services.get_matching_slots for how an unset value falls back to showing every group.", max_length=50),
        ),
    ]
