# Generated by Django 5.2.7 on 2026-05-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('credit_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='departments.department')),
            ],
            options={
                'indexes': [models.Index(fields=['department', 'code'], name='units_unit_departm_783323_idx')],
                'unique_together': {('department', 'code'), ('department', 'name')},
            },
        ),
    ]
