# Generated by Django 5.2.7 on 2026-05-22 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('duration_years', models.PositiveSmallIntegerField(default=3)),
                ('award_type', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='departments.department')),
            ],
            options={
                'indexes': [models.Index(fields=['department', 'code'], name='programs_pr_departm_f0045e_idx')],
                'unique_together': {('department', 'code'), ('department', 'name')},
            },
        ),
    ]
