# Generated by Django 5.2.7 on 2026-05-22 13:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('lecturers', '0001_initial'),
        ('programs', '0001_initial'),
        ('rooms', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_file', models.FileField(upload_to='uploads/timetables/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xlsm'])])),
                ('upload_type', models.CharField(choices=[('timetable', 'Timetable')], default='timetable', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('validating', 'Validating'), ('processing', 'Processing'), ('partial', 'Partial'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('error_summary', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_uploads', to='departments.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_uploads', to='programs.program')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timetable_upload',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadConflictReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conflict_type', models.CharField(choices=[('room', 'Room Conflict'), ('lecturer', 'Lecturer Conflict'), ('overlap', 'Overlapping Session'), ('duplicate', 'Duplicate Session'), ('mapping', 'Mapping Conflict')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('affected_lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_conflict_reports', to='lecturers.lecturer')),
                ('affected_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_conflict_reports', to='rooms.room')),
                ('affected_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_conflict_reports', to='units.unit')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_reports', to='uploads.timetableupload')),
            ],
            options={
                'db_table': 'timetable_upload_conflict_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='uploads.timetableupload')),
            ],
            options={
                'db_table': 'timetable_upload_processing_log',
                'ordering': ['row_number', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='timetableupload',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='idx_upload_user_date'),
        ),
        migrations.AddIndex(
            model_name='timetableupload',
            index=models.Index(fields=['processing_status', 'uploaded_at'], name='idx_upload_status_date'),
        ),
        migrations.AddIndex(
            model_name='timetableupload',
            index=models.Index(fields=['department', 'uploaded_at'], name='idx_upload_department_date'),
        ),
        migrations.AddIndex(
            model_name='timetableupload',
            index=models.Index(fields=['program', 'uploaded_at'], name='idx_upload_program_date'),
        ),
        migrations.AddIndex(
            model_name='uploadconflictreport',
            index=models.Index(fields=['upload', 'conflict_type'], name='idx_upload_conflict_type'),
        ),
        migrations.AddIndex(
            model_name='uploadconflictreport',
            index=models.Index(fields=['upload', 'severity'], name='idx_upload_conflict_severity'),
        ),
        migrations.AddIndex(
            model_name='uploadprocessinglog',
            index=models.Index(fields=['upload', 'row_number'], name='idx_upload_log_row'),
        ),
        migrations.AddIndex(
            model_name='uploadprocessinglog',
            index=models.Index(fields=['upload', 'status'], name='idx_upload_log_status'),
        ),
    ]
