# Generated by Django 5.1 on 2026-06-09 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableupload',
            name='uploaded_file',
            field=models.FileField(upload_to='uploads/timetables/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsm', 'xlsx'])]),
        ),
    ]
