# Generated by Django 5.1 on 2026-06-09 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_timetableupload_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableupload',
            name='uploaded_file',
            field=models.FileField(upload_to='uploads/timetables/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xlsm'])]),
        ),
    ]
