# Generated by Django 5.2.7 on 2026-05-22 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_date', models.DateField()),
                ('key', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('dimensions', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-metric_date', 'key'],
            },
        ),
    ]
