name: Deploy SMARTTT Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy via Docker Compose
        run: |
          cd /var/www/smarttt/SMARTTT_BACKEND
          git pull origin main
          docker compose -f docker-compose.prod.yml up -d --build
          docker image prune -f

